[api]
base_url = "https://cricbuzz-cricket.p.rapidapi.com/matches/v1/recent "   # Replace with actual cricket API base URL
api_key = "82f2cffbafmshfb308b9b00053fcp1d7d46jsn45b3a8b0186f'"               # Put your real API key here